
get_docs:
	wget http://www.atmel.com/images/atmel-7766-8-bit-avr-atmega16u4-32u4_datasheet.pdf -O atmega32u4.pdf
	wget https://www.pjrc.com/teensy/card2a.pdf -O teensy2p0_pins.pdf
	wget https://www.pjrc.com/teensy/schematic2.gif -O teensy2p0_sch.gif
	wget http://www.onsemi.com/pub_link/Collateral/PCA9655E-D.PDF -O pca9655e_ioe.pdf
	wget http://www.ti.com/lit/ds/symlink/pca9306.pdf -O pca9306_shift.pdf
	wget http://www.diodes.com/_files/datasheets/AP7313.pdf -O ap7303_reg.pdf
	wget http://www.ck-components.com/14409/pts645_25apr13.pdf/ -O pts645_sw.pdf
	wget https://www.fairchildsemi.com/datasheets/KS/KSA1298.pdf -O ksa1298_pnp.pdf
	wget http://www.cui.com/product/resource/sj-4351x.pdf -O sj4351_trrs.pdf
	wget --header="User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0" http://media.digikey.com/pdf/Data%20Sheets/Optek%20PDFs/OVLLx8C7.pdf -O ovllx8c7_leds.pdf
	wget --header="User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0" http://media.digikey.com/pdf/Data%20Sheets/Everlight%20PDFs/PT908-7B-F.pdf -O pt908-7b-f_phototrans.pdf
	wget http://optoelectronics.liteon.com/upload/download/DS-50-92-0009/S_110_E302.pdf -O s_110_e302_irled.pdf

clean:
	rm -f *.pdf *.gif
